config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pics
  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    
    before_action :find_pic, only: [:edit, :update, :show, :destroy]
    skip_before_action :verify_authenticity_token, :only => [:destroy]
    
    def index
        @pics = Pic.all.order("created_at DESC")
    end
    
    def show 
    end

    def new
        @pic = current_user.pics.build
    end

    def create
        @pic = current_user.pics.build(pic_params)
        if @pic.save
            redirect_to @pic, notice: "Yess! It was posted!"
        else
            render "new"
        end
            
    end
    def edit
    end
    def update
        if @pic.update(pic_params)
            redirect_to @pic, notice: "Congrats! Pic was update"
        else
            render 'edit'
        end
    end
    def destroy
        @pic.destroy
        redirect_to root_path
    end


    private
    
    def pic_params
        params.require(:pic).permit(:title, :description)
    end

    def find_pic
        @pic = Pic.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Moonbow
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csp_meta_tag
%body
  -flash.each do |name, msg|
    =content_tag :div, msg, class: "alert alert-info"
  =yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
  - if @pic.errors.any?
    #errors
      %h2 
        = pluralize(@pic.errors.count, "error")
        prevented this Pic from saving
        %ul
          - @pic.errors.full_message.each do |msg|
            %li= msg

  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form_control' }

  = f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
%h1 Fic Pic!
= render 'form'
= link_to "Cancel", pic_path

app/views/pics/index.html.haml
- @pics.each do |pic|
  %h2= link_to pic.title, pic
= link_to "Gram It" , new_pic_path

app/views/pics/new.html.haml
%h1 Post Pic
= render 'form'
= link_to "Back", root_path

app/views/pics/show.html.haml
%h1= @pic.title
%p= @pic.description
%p
Pic by
= @pic.user.email
%br
= link_to "Back", root_path
= link_to "Edit", edit_pic_path
= link_to "Delete", pic_path, method: :delete, data: {confirm:"Are you sure?"}